---
- name: Ensure /etc/htb directory exists
  file:
    path: /etc/htb
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Copy hackthebox scripts
  copy:
    src: files/vpnpanel.sh
    dest: /etc/htb/vpnpanel.sh
    owner: root
    group: root
    mode: 0755
  become: true
  become_method: sudo

- name: Configure MATE panel
  shell: dconf load /org/mate/panel/ < "{{ role_path }}/files/mate-panel.conf"

